version: "3.7"

services:
    backend:
        container_name: sir-note-backend
        # image: docker.pkg.github.com/minhthong582000/thiet-ke-mang/tasks-management-api:latest
        build:
            context: ./backend
        restart: always
        volumes:
            - sir-note-backend:/usr/src/app
        ports:
            - 8080:8080
        env_file:
            - ./backend/.env
        # network_mode: host
        networks:
            sirnote-net:
                ipv4_address: 172.28.1.4
        extra_hosts:
            - docker.host:172.17.0.1

    frontend:
        container_name: sir-note-frontend
        # image: docker.pkg.github.com/minhthong582000/thiet-ke-mang/tasks-management-fe:latest
        build:
            context: ./frontend
        restart: always
        ports:
            - 80:80
        networks:
            - sirnote-net

volumes:
    sir-note-backend:
    sir-note-frontend:
networks:
    sirnote-net:
        name: sirnote-net
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
